build(pom.xml): update robotframework-seleniumlibrary to 3.12.0.1
This commit also updates the following required dependencies:
- selenium to 3.12.0
- htmlunit-driver to 2.28
- htmlunit to 2.28

Also, in order to fix a conflict between dependencies, I switched to
my own fork of the robotframework-maven-plugin. Newer htmlunit uses a
method from commons-io that was introduced in version 2.3. At the same
time, robotframework-maven-plugin depends on plexus-io:2.7 that pulls
commons-io:2.2 Because the old version of the library was in classpath,
the tests were failing with the error:

java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;

My fork has updated version of plexus-io (and commons-io) that fixes
the conflict.

Changelogs:
- https://seleniumhq.wordpress.com/2016/07/29/announcing-selenium-3-0-beta1/
- https://seleniumhq.wordpress.com/2016/10/13/selenium-3-0-out-now/
- https://github.com/SeleniumHQ/selenium/blob/selenium-3.14.0/java/CHANGELOG

TODO: fix the build
TODO: add changelogs
TODO: update selenium to 3.14.0
TODO: update htmlunit to 2.32 or 2.33
TODO: update htmlunit-driver to 2.32.1